### ISSUE TITLE
Excel crashes when sorting is applied

### ISSUE THREAD

**Issue by glavind** [awalker89/openxlsx#152]
The following code generates an excel file with around 400k observations in 1 column, 
```
wb <- createWorkbook() # Create workbook
addWorksheet(wb, sheetName="data") # Create sheet
writeData(wb, "data", dt.data, withFilter=T, colNames=T, rowNames=T) # Write data
openXL(wb)
```
When sorting using the applied filter, excel crashes.

Might be related to [this issue](http://stackoverflow.com/questions/33082375/adding-autofilter-and-sorting-causes-excel-to-crash)?

Cheers

**Comment by awalker89** [comment]
This is fixed in dev version.

**Comment by winterschlaefer** [comment]
The problem persists in the dev version when having more than one sheet:

```R
library(openxlsx)

wb <- createWorkbook() 

addWorksheet(wb, sheetName="data") 
addWorksheet(wb, sheetName="data2") 

dat <- data.frame(n = rnorm(100))

writeData(wb, "data", dat, withFilter=T, colNames=T, rowNames=F) 
writeData(wb, "data2", dat, withFilter=T, colNames=T, rowNames=F) 

saveWorkbook(wb = wb, file = "test.xlsx", overwrite = TRUE)
```
When sorting using the applied filter, excel crashes.

> packageVersion("openxlsx")
[1] ‘4.1.1’
>
