### ISSUE TITLE
stacking styles bug still biting

### ISSUE THREAD

**Issue by t-kalinowski** [awalker89/openxlsx#215]
This is as minimal an example I could muster. Some edge case is being triggered here that disappears when I try to isolate further.

The R object can be downloaded here: https://dl.dropboxusercontent.com/u/4477501/workbook_data_bug_report.rda
#### setup

```
library(openxlsx)

load("workbook_data_bug_report.rda")
ws$sheet_name <- "WG"

wb <- createWorkbook()
addWorksheet(wb, ws$sheet_name)

openxlsx::writeData(
  wb,
  ws$sheet_name,
  ws$text,
  startRow = 1,
  startCol = 1,
  colNames = FALSE, borders = "all"
)


for (i in seq_along(ws$styleKey[1:9])) {
  posToFormat <- which(ws$style == names(ws$styleKey)[i], arr.ind = TRUE)
  openxlsx::addStyle( wb, ws$sheet_name,
    ws$styleKey[[i]],
    rows = posToFormat[, 1],
    cols = posToFormat[, 2],
    gridExpand = FALSE,
    stack = TRUE 
  )
}

openXL(wb) # fine till here

```

On this iteration of the loop, some formatting is lost in cells adjacent to those styled.

```
i <- 10

posToFormat <- which(ws$style == names(ws$styleKey)[i], arr.ind = TRUE)
openxlsx::addStyle( wb, ws$sheet_name,
                    ws$styleKey[[i]],
                    rows = posToFormat[, 1],
                    cols = posToFormat[, 2],
                    gridExpand = FALSE,
                    stack = TRUE 
)

openXL(wb) # cells I9, J10, K11 have lost formatting
```

**Comment by awalker89** [comment]
I've the this code to from 1:9 on the left and 1:10 on the right.  The cells I9, J10, K11 look fine. Am I missing something or has this been fixed now?

![image](https://cloud.githubusercontent.com/assets/7400673/20034672/8c438fea-a41a-11e6-869d-f23af4551fca.png)

**Comment by t-kalinowski** [comment]
Hi Alex. I was able to reproduce the bug with the version just before all the commits this past week/weekend (  version 3.1.23 I think). This is what the output looked like:
![image](https://cloud.githubusercontent.com/assets/8462255/20103006/3889d7d8-a596-11e6-85fa-ce3f51abc4f1.png)

Now, when I update to the current dev version, and i rerun the same code as above, I get the following error: 
![image](https://cloud.githubusercontent.com/assets/8462255/20103086/8c36076c-a596-11e6-99ce-745ac797604e.png)
and when I click "Yes": 
![image](https://cloud.githubusercontent.com/assets/8462255/20103097/9696e1c2-a596-11e6-950a-c8b7625cd9d5.png)

However, then the formatting issues seems to be resolved. This is the output after excel repairs the XML errors: 
![image](https://cloud.githubusercontent.com/assets/8462255/20103133/bbce2914-a596-11e6-8e93-ebd0882e275c.png)

**Comment by awalker89** [comment]
Thanks for sending this through.  The bug causing unreadable content should be fixed now.

**Comment by t-kalinowski** [comment]
I still get the error running the setup code above:
![image](https://cloud.githubusercontent.com/assets/8462255/20186795/66fcd1d8-a73f-11e6-9fcd-7fe0553d2a1b.png)

```
> sessionInfo()$otherPkgs$openxlsx$Version
[1] "3.1.25"
```
