### ISSUE TITLE
openxlsx 2.4.0 and libre office

### ISSUE THREAD

**Issue by richardprichard** [awalker89/openxlsx#74]
I've updated to the latest package version and openxlsx will now not open files that have been saved with libreoffice. If I reopen and save them in Windows Excel they are fine. This applies to the individual sheets within a workbook:

> master
> [1] "~/Dropbox/PQF/masters/master_lookups_new.xlsx"
> lookups <- readWorkbook(master, 'lookups') # works
> places <- readWorkbook(master, 'places')
> Error in worksheets[[sheet]] : subscript out of bounds

Is there any other info I should provide ?

**Comment by awalker89** [comment]
Can you please email an example xlsx file to Alexander.Walker1989@gmail.com

**Comment by redmode** [comment]
It seems to be reading next sheet to what you specified. Thus it's not possible to read first sheet in the workbook saved in LibreOffice.

**Comment by awalker89** [comment]
d0470155c762a03e9e240434857a6088c61cca77 should fix this.  Still performing testing.

**Comment by stevepowell99** [comment]
same problem here.

**Comment by awalker89** [comment]
update with devtools::install_github("awalker89/openxlsx")

**Comment by richardprichard** [comment]
Thanks for getting on to this. The github version is corrupt (for me) :

> devtools::install_github("awalker89/openxlsx")
Downloading github repo awalker89/openxlsx@master
Installing openxlsx
'/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmp1pF4Zn/devtoolsfc075bb1897/awalker89-openxlsx-f89b3c0'  \
  --library='/home/richardc/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘openxlsx’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/richardc/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/richardc/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c cppFunctions.cpp -o cppFunctions.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o openxlsx.so RcppExports.o cppFunctions.o -L/usr/lib/R/lib -lR
installing to /home/richardc/R/x86_64-pc-linux-gnu-library/3.2/openxlsx/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (openxlsx)
Reloading installed openxlsx
Error in get(method, envir = home) : 
  lazy-load database '/home/richardc/R/x86_64-pc-linux-gnu-library/3.2/openxlsx/R/openxlsx.rdb' is corrupt
In addition: Warning message:
In get(method, envir = home) : internal error -3 in R_decompress1

**Comment by septra** [comment]
Updated from R version 3.1 to 3.2 and `Error in worksheets[[sheet]] : subscript out of bounds` turned up while using the read.xlsx function.

Updated the package with devtools::install_github("awalker89/openxlsx") after restarting R

Now I'm getting this:
`Error in read.xlsx.default(xlsxFile = xlsxFile, sheet = sheet, startRow = startRow,  : 
  Workbook has no worksheets`

**Comment by awalker89** [comment]
Can you please send me an xlsx file to Alexander.Walker1989@gmail.com where this error occurs.

**Comment by awalker89** [comment]
I believe this is fixed now?

**Comment by septra** [comment]
Yes. Tried on multiple files and its working smoothly.

**Comment by Figuera** [comment]
May I reopen this? Because the problem is still happening with me.

When I edit and save with libreoffice and then try to open with openxlsx i get:

`Error in borders[[as.integer(s[["borderId"]]) + 1L]] :
  subscript out of bounds`

Again if I open with Microsoft Excel and then save everything goes back to normal.

I already ran devtools::install_github("awalker89/openxlsx") and tried again (and restart and tried again) but that doesn't helped.

The file I am trying to load is attached in this message:
[sobrevida.xlsx](https://github.com/awalker89/openxlsx/files/678693/sobrevida.xlsx)
